Feature/db challenge3
M9k21/quelcode-db pull request #4
Opened 2020-08-16 07:55 UTC by M9k21

データベース課題3 問題番号001〜005
SQL文の作成・実行

2020-08-19 11:53 UTC, n06Ar requested changes
レビューしました
ご確認をお願いします

2020-08-19 11:53 UTC, n06Ar commented on db/db-challenge3/db-001/db-001.sql
> +
`COMMIT`と`user_profile` テーブルへの `Insert`がありませんが意図はありますか？

2020-08-19 11:53 UTC, n06Ar commented on db/db-challenge3/db-001/db-001.sql
> +
`BEGIN`がないです

2020-08-19 11:53 UTC, n06Ar commented on db/db-challenge3/db-001/db-001.sql
> +
`COMMIT`と`user_profile` テーブルへの `Insert`がありませんが意図はありますか？

2020-08-19 11:53 UTC, n06Ar commented on db/db-challenge3/db-002/db-002.sql
> +INSERT INTO
`BEGIN`と`COMMIT`がないです。
商用環境とかでDBを直接操作する場合だとSQLで事故を起こした時にRollBackで戻せるので、
トランザクションは基本的に入れるようにしてください。

2020-08-19 11:53 UTC, n06Ar commented on db/db-challenge3/db-003/db-003.sql
> +INSERT INTO
`BEGIN`と`COMMIT`がないです。
商用環境とかでDBを直接操作する場合だとSQLで事故を起こした時にRollBackで戻せるので、
トランザクションは基本的に入れるようにしてください。

2020-08-19 11:53 UTC, n06Ar commented on db/db-challenge3/db-004/db-004.sql
> +    (
`BEGIN`と`COMMIT`がないです。
商用環境とかでDBを直接操作する場合だとSQLで事故を起こした時にRollBackで戻せるので、
トランザクションは基本的に入れるようにしてください。

2020-08-19 11:53 UTC, n06Ar commented on db/db-challenge3/db-004/db-004.sql
> + create_user_id AS 'update_user_id'
`create_user_id `を`update_user_id`にした意図はなんでしょうか？
作成者=更新者でも更新者にデータを入れるようにしてください

2020-08-19 11:53 UTC, n06Ar commented on db/db-challenge3/db-005/db-005.sql
> +INSERT INTO
`BEGIN`と`COMMIT`がないです。
商用環境とかでDBを直接操作する場合だとSQLで事故を起こした時にRollBackで戻せるので、
トランザクションは基本的に入れるようにしてください。

2020-08-19 23:51 UTC, M9k21 commented on db/db-challenge3/db-001/db-001.sql
> +
`user_profile`テーブルについて、id以外の項目が空だったためINSERT文を作成していませんでしたが空の項目をNULLにすることで対応しました。  
- INSERT文 8f98b23
- トランザクション eaba19d

2020-08-19 23:52 UTC, M9k21 commented on db/db-challenge3/db-001/db-001.sql
> +
トランザクションを実装しました
eaba19d

2020-08-19 23:56 UTC, M9k21 commented on db/db-challenge3/db-001/db-001.sql
> +
`user_profile`テーブルについて、id以外の項目が空だったためINSERT文を作成していませんでしたが空の項目をNULLにすることで対応しました。

- INSERT文 5828dba
- トランザクション eaba19d

2020-08-19 23:58 UTC, M9k21 commented on db/db-challenge3/db-002/db-002.sql
> +INSERT INTO
トランザクションを実装しました
c25b612

2020-08-19 23:59 UTC, M9k21 commented on db/db-challenge3/db-003/db-003.sql
> +INSERT INTO
トランザクションを実装しました
f87ea4f

2020-08-20 00:00 UTC, M9k21 commented on db/db-challenge3/db-004/db-004.sql
> +    (
トランザクションを実装しました
1d48140

2020-08-20 00:10 UTC, M9k21 commented on db/db-challenge3/db-004/db-004.sql
> + create_user_id AS 'update_user_id'
設計の段階でmessagesテーブルに更新者idのカラムを作っておらず、課題の表示に合わせるために今回このような形をとりました。

2020-08-20 00:11 UTC, M9k21 commented on db/db-challenge3/db-005/db-005.sql
> +INSERT INTO
トランザクションを実装しました
b5033ed

2020-08-20 00:32 UTC, M9k21 commented
@n06Ar 
以下の通り修正しました。
 - db-001~db-005におけるトランザクションの実装
 - db-001.sqlへのINSERT文の追記

db-004.sqlについては指摘いただいた通りに修正できていない部分がありますが
コメントの方に返信させていただいております。ご確認よろしくお願いいたします。

2020-08-20 15:26 UTC, n06Ar requested changes
コメントに返信をしました
ご確認をお願いします

2020-08-20 15:26 UTC, n06Ar commented on db/db-challenge3/db-004/db-004.sql
> + create_user_id AS 'update_user_id'
現状DBには`messages`テーブルには更新者idがない理解で良いでしょうか？
もし現状もないのであれば、お手数ですが更新者idのカラムを追加して対応をお願いします。

2020-08-20 15:32 UTC, n06Ar commented
これはimo的なコメントです
指摘の仕方が悪かったので申し訳ないのですが、`BEGIN`と`COMMIT`は1つのSQLファイルにつき一つで良かったです。
商用（本番）環境でSQLを実行する時は、`COMMIT`はコメントアウトして`SELECT`で問題がないか確認をして問題がなければ`COMMIT`をする手順を踏みます（問題があれば`ROLLBACK`します）
今回のSQLを見る限り一つ一つトランザクションを貼る必要はないので、まとめてやってしまう方針で良いです

2020-08-21 00:49 UTC, M9k21 commented on db/db-challenge3/db-004/db-004.sql
> + create_user_id AS 'update_user_id'
カラムを追加し、INSERT文の内容を修正しました。 
- `messages`テーブルに`update_user_id`カラムを追加 da14bef
 - `update_user_id`カラムのデータを追記 6ebb016

2020-08-21 00:55 UTC, M9k21 commented
以下の通り修正しました。ご確認お願いいたします。

 - `messages`テーブルにカラムを追加
 - db-004.sqlのINSERT文を修正

2020-08-22 03:01 UTC, n06Ar approved these changes
LGTMです！

2020-08-22 13:38 UTC, M9k21 commented
データベース課題3 問題番号006〜010
SQL文を作成しました。ご確認お願いいたします。

2020-08-23 07:05 UTC, ykyk1218 commented on db/db-challenge3/db-007/db-007.sql
> +    END AS allow_file_send,
全く問題ないのですが、珍しいなと思ったのでコメントです。

SQL をゴリゴリ書く現場はわからないのですが、普通の Web アプリケーション開発で SQL の CASE 文を書くケースはほとんどないかと思います。
そのままフラグの値を受け取って、プログラムの方で表示名を変えるパターンになるかと。

2020-08-23 07:11 UTC, ykyk1218 commented on db/db-challenge3/db-008/db-008.sql
> +    SUBSTRING(p.participated_at, 1, 10) AS '参加日時'
participated_at の値は 2020-01-01 12:00:00
みたいな値ですかね...？

substring で先頭から 10 文字でも良いですが、日付型のフォーマットなので DATE_FORMAT 関数を使ってあげる方が良いかなと思います。

2020-08-23 07:15 UTC, ykyk1218 commented on db/db-challenge3/db-009/db-009.sql
> +    COUNT(*) DESC
ここの order by で as で指定をしたカラム名って使用できなかったでしたっけ...？
COUNT(*) だけだとなんのカラムなのかわかりずらいので、カラム名を指定した方がいいかなと思いました。

2020-08-24 02:29 UTC, M9k21 commented on db/db-challenge3/db-007/db-007.sql
> +    END AS allow_file_send,
現場でCASE文を書くことはあまりないとのことで、勉強になりました。

今回は問題文の中に
> ファイル送信が許可されているときは「許可」、許可されていないときは「禁止」と表示

という指示があったのでCASE演算子を使って記述しました。

2020-08-24 02:32 UTC, M9k21 commented on db/db-challenge3/db-008/db-008.sql
> +    SUBSTRING(p.participated_at, 1, 10) AS '参加日時'
DATE_FORMAT関数を使用した記述に修正しました。

05cd48d

2020-08-24 02:34 UTC, M9k21 commented on db/db-challenge3/db-009/db-009.sql
> +    COUNT(*) DESC
ORDER BY句のカラム名をASで指定したカラム名に修正しました。

356e193

2020-08-24 02:38 UTC, M9k21 commented
以下の通り修正しました。ご確認お願いいたします。
- `008.sql`
参加日時を取得する際の関数を修正
- `009.sql`
ORDER BY句のカラム名を修正

2020-08-25 11:50 UTC, ykyk1218 approved these changes
良さそうです 👍

2020-08-25 11:50 UTC, ykyk1218 commented on db/db-challenge3/db-010/db-010.sql
> +            MAX(created_at)
自分だったら created_at で order by して limit 1 で取ってきたかも。

でも MAX を使う場合とどっちがいいのかわからないので、後で検証してみようかなって思ってます。

2020-08-26 02:21 UTC, M9k21 commented
データベース課題3 問題番号011〜014
SQL文を作成しました。ご確認お願いいたします。

2020-08-26 11:54 UTC, n06Ar reviewed
imo的なコメントをしました
興味がありましたら読んでみてください

2020-08-26 11:54 UTC, n06Ar commented on db/db-challenge3/db-011/db-011.sql
> +    created_at >= '2020-04-26 09:00'
Betweenを使っても良いです
```sql
created_at Between '2020-04-26 09:00:00' and '2020-04-26 11:30:00'
```

2020-08-26 11:54 UTC, n06Ar commented on db/db-challenge3/db-012/db-012.sql
> +    id IN (
imo的なコメントです
この行をNOT IN にして31行目`user_id = 1`にする方法があります
このSQLの場合だと`participation`テーブルのレコードが、`user_id = 1`でないレコードが多い場合にパフォーマンスがこちらの方が高くなります

2020-08-26 11:54 UTC, n06Ar commented on db/db-challenge3/db-014/db-014.sql
> +
今回は問題なさそうなので問題ないのですが、外部キー制約をつけていた場合は`set foreign_key_checks = 0;`を実行してから物理削除をDELETEを実行するようにしてください

2020-08-26 12:04 UTC, n06Ar approved these changes
LGTMです！

今回課題で指摘されていないので気に留める必要はないのですが、一応ですが業務では考えておいた方が良いことを書いておきます

UPDATEやDELETEなどレコードの削除や書き換えを行うSQLで画像やdumpが必要な場合は、実行前と実行後の画像を取得するようにしてください
なぜなら、実行直前から実行直後の状態かSQLによる変更なのか確認ができないためです
（業務で証跡として実行前と実行後の画像などを取得することが必須なことがあります）
今回の場合ですと他の課題の画像があるので問題がないのではと思われがちですが、実行後の画像だけだと直近が実行後の状態でなかった根拠がないため正しいことを証明することができません

2020-08-30 11:35 UTC, merged